GivenStories: voice_GG/ui/Endurance/API/@DefineHMI_URI.story,
			  voice_GG/ui/Endurance/API/@ExternalSIPPhones.story,
			  voice_GG/ui/Endurance/API/FirstChangeMission.story,
			  voice_GG/ui/Endurance/API/FirstRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/FirstRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/FirstRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/FirstRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/FirstRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/FirstRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/FirstRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/FirstRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/FirstRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/FirstRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/SecondChangeMission.story,
			  voice_GG/ui/Endurance/API/SecondRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/SecondRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/SecondRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/SecondRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/SecondRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/SecondRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/SecondRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/SecondRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/SecondRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/SecondRoundOfCalls.story,
			  voice_GG/ui/Endurance/API/FirstChangeMission.story,
			  voice_GG/ui/Endurance/API/@CleanupCATSPhones.story

Scenario: Wait 1 millisecond (needed for given stories to be executed)
Then waiting for 1 millisecond